// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 3 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int statusencoder_3 = 3;
	/// <summary>PID: 3 | Type: read</summary>
	public const int statusencoder = 3;
	/// <summary>PID: 4 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int statusdecoder_4 = 4;
	/// <summary>PID: 4 | Type: read</summary>
	public const int statusdecoder = 4;
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitrateencoder_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int currentcompressedbitrateencoder = 5;
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int currentcompressedbitratedecoder_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int currentcompressedbitratedecoder = 6;
	/// <summary>PID: 7 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int autochromaweight_7 = 7;
	/// <summary>PID: 7 | Type: read</summary>
	public const int autochromaweight = 7;
	/// <summary>PID: 8 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int chromaweight_8 = 8;
	/// <summary>PID: 8 | Type: read</summary>
	public const int chromaweight = 8;
	/// <summary>PID: 9 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int losslessmode_9 = 9;
	/// <summary>PID: 9 | Type: read</summary>
	public const int losslessmode = 9;
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int progressionorder_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int progressionorder = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockwidth_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int codeblockwidth = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int codeblockheight_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int codeblockheight = 12;
	/// <summary>PID: 55 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedcurrentcompressedbitrateencoder_55 = 55;
	/// <summary>PID: 55 | Type: read</summary>
	public const int savedcurrentcompressedbitrateencoder = 55;
	/// <summary>PID: 56 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedcurrentcompressedbitratedecoder_56 = 56;
	/// <summary>PID: 56 | Type: read</summary>
	public const int savedcurrentcompressedbitratedecoder = 56;
	/// <summary>PID: 57 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedautochromaweight_57 = 57;
	/// <summary>PID: 57 | Type: read</summary>
	public const int savedautochromaweight = 57;
	/// <summary>PID: 58 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedchromaweight_58 = 58;
	/// <summary>PID: 58 | Type: read</summary>
	public const int savedchromaweight = 58;
	/// <summary>PID: 59 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedlosslessmode_59 = 59;
	/// <summary>PID: 59 | Type: read</summary>
	public const int savedlosslessmode = 59;
	/// <summary>PID: 60 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedprogressionorder_60 = 60;
	/// <summary>PID: 60 | Type: read</summary>
	public const int savedprogressionorder = 60;
	/// <summary>PID: 61 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedcodeblockwidth_61 = 61;
	/// <summary>PID: 61 | Type: read</summary>
	public const int savedcodeblockwidth = 61;
	/// <summary>PID: 62 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int savedcodeblockheight_62 = 62;
	/// <summary>PID: 62 | Type: read</summary>
	public const int savedcodeblockheight = 62;
	public class Write
	{
		/// <summary>PID: 103 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int statusencoder_103 = 103;
		/// <summary>PID: 103 | Type: write</summary>
		public const int statusencoder = 103;
		/// <summary>PID: 104 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int statusdecoder_104 = 104;
		/// <summary>PID: 104 | Type: write</summary>
		public const int statusdecoder = 104;
		/// <summary>PID: 107 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int autochromaweight_107 = 107;
		/// <summary>PID: 107 | Type: write</summary>
		public const int autochromaweight = 107;
		/// <summary>PID: 108 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int chromaweight_108 = 108;
		/// <summary>PID: 108 | Type: write</summary>
		public const int chromaweight = 108;
		/// <summary>PID: 109 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int losslessmode_109 = 109;
		/// <summary>PID: 109 | Type: write</summary>
		public const int losslessmode = 109;
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int progressionorder_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int progressionorder = 110;
	}
}
public class WriteParameters
{
	/// <summary>PID: 103  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Statusencoder {get { return Protocol.GetParameter(103); }set { Protocol.SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Statusdecoder {get { return Protocol.GetParameter(104); }set { Protocol.SetParameter(104, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Autochromaweight {get { return Protocol.GetParameter(107); }set { Protocol.SetParameter(107, value); }}
	/// <summary>PID: 108  | Type: write</summary>
	public System.Object Chromaweight {get { return Protocol.GetParameter(108); }set { Protocol.SetParameter(108, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Losslessmode {get { return Protocol.GetParameter(109); }set { Protocol.SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Progressionorder {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Statusencoder_3 { get; set; }
	object Statusencoder { get; set; }
	object Statusdecoder_4 { get; set; }
	object Statusdecoder { get; set; }
	object Currentcompressedbitrateencoder_5 { get; set; }
	object Currentcompressedbitrateencoder { get; set; }
	object Currentcompressedbitratedecoder_6 { get; set; }
	object Currentcompressedbitratedecoder { get; set; }
	object Autochromaweight_7 { get; set; }
	object Autochromaweight { get; set; }
	object Chromaweight_8 { get; set; }
	object Chromaweight { get; set; }
	object Losslessmode_9 { get; set; }
	object Losslessmode { get; set; }
	object Progressionorder_10 { get; set; }
	object Progressionorder { get; set; }
	object Codeblockwidth_11 { get; set; }
	object Codeblockwidth { get; set; }
	object Codeblockheight_12 { get; set; }
	object Codeblockheight { get; set; }
	object Encodertitle__fixed { get; set; }
	object Decodertitle__fixed { get; set; }
	object Savedcurrentcompressedbitrateencoder_55 { get; set; }
	object Savedcurrentcompressedbitrateencoder { get; set; }
	object Savedcurrentcompressedbitratedecoder_56 { get; set; }
	object Savedcurrentcompressedbitratedecoder { get; set; }
	object Savedautochromaweight_57 { get; set; }
	object Savedautochromaweight { get; set; }
	object Savedchromaweight_58 { get; set; }
	object Savedchromaweight { get; set; }
	object Savedlosslessmode_59 { get; set; }
	object Savedlosslessmode { get; set; }
	object Savedprogressionorder_60 { get; set; }
	object Savedprogressionorder { get; set; }
	object Savedcodeblockwidth_61 { get; set; }
	object Savedcodeblockwidth { get; set; }
	object Savedcodeblockheight_62 { get; set; }
	object Savedcodeblockheight { get; set; }
	object Statusencoder_103 { get; set; }
	object Statusdecoder_104 { get; set; }
	object Autochromaweight_107 { get; set; }
	object Chromaweight_108 { get; set; }
	object Losslessmode_109 { get; set; }
	object Progressionorder_110 { get; set; }
	object Minusonevalue__fixed { get; set; }
	object Zerovalue__fixed { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statusencoder_3 {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 3  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Statusencoder {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statusdecoder_4 {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Statusdecoder {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitrateencoder_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Currentcompressedbitrateencoder {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Currentcompressedbitratedecoder_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Currentcompressedbitratedecoder {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_7 {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 7  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Autochromaweight {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 8  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_8 {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 8  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Chromaweight {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_9 {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 9  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Losslessmode {get { return GetParameter(9); }set { SetParameter(9, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Progressionorder {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockwidth_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockwidth {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Codeblockheight_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Codeblockheight {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: fixed</summary>
	public System.Object Encodertitle__fixed {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: fixed</summary>
	public System.Object Decodertitle__fixed {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 55  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedcurrentcompressedbitrateencoder_55 {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 55  | Type: read</summary>
	public System.Object Savedcurrentcompressedbitrateencoder {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 56  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedcurrentcompressedbitratedecoder_56 {get { return GetParameter(56); }set { SetParameter(56, value); }}
	/// <summary>PID: 56  | Type: read</summary>
	public System.Object Savedcurrentcompressedbitratedecoder {get { return GetParameter(56); }set { SetParameter(56, value); }}
	/// <summary>PID: 57  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedautochromaweight_57 {get { return GetParameter(57); }set { SetParameter(57, value); }}
	/// <summary>PID: 57  | Type: read</summary>
	public System.Object Savedautochromaweight {get { return GetParameter(57); }set { SetParameter(57, value); }}
	/// <summary>PID: 58  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedchromaweight_58 {get { return GetParameter(58); }set { SetParameter(58, value); }}
	/// <summary>PID: 58  | Type: read</summary>
	public System.Object Savedchromaweight {get { return GetParameter(58); }set { SetParameter(58, value); }}
	/// <summary>PID: 59  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedlosslessmode_59 {get { return GetParameter(59); }set { SetParameter(59, value); }}
	/// <summary>PID: 59  | Type: read</summary>
	public System.Object Savedlosslessmode {get { return GetParameter(59); }set { SetParameter(59, value); }}
	/// <summary>PID: 60  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedprogressionorder_60 {get { return GetParameter(60); }set { SetParameter(60, value); }}
	/// <summary>PID: 60  | Type: read</summary>
	public System.Object Savedprogressionorder {get { return GetParameter(60); }set { SetParameter(60, value); }}
	/// <summary>PID: 61  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedcodeblockwidth_61 {get { return GetParameter(61); }set { SetParameter(61, value); }}
	/// <summary>PID: 61  | Type: read</summary>
	public System.Object Savedcodeblockwidth {get { return GetParameter(61); }set { SetParameter(61, value); }}
	/// <summary>PID: 62  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Savedcodeblockheight_62 {get { return GetParameter(62); }set { SetParameter(62, value); }}
	/// <summary>PID: 62  | Type: read</summary>
	public System.Object Savedcodeblockheight {get { return GetParameter(62); }set { SetParameter(62, value); }}
	/// <summary>PID: 103  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statusencoder_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Statusdecoder_104 {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 107  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Autochromaweight_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 108  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Chromaweight_108 {get { return GetParameter(108); }set { SetParameter(108, value); }}
	/// <summary>PID: 109  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Losslessmode_109 {get { return GetParameter(109); }set { SetParameter(109, value); }}
	/// <summary>PID: 110  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Progressionorder_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 999  | Type: fixed</summary>
	public System.Object Minusonevalue__fixed {get { return GetParameter(999); }set { SetParameter(999, value); }}
	/// <summary>PID: 1000  | Type: fixed</summary>
	public System.Object Zerovalue__fixed {get { return GetParameter(1000); }set { SetParameter(1000, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
