// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 1 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodertitleparameter_1 = 1;
	/// <summary>PID: 1 | Type: read</summary>
	public const int encodertitleparameter = 1;
	/// <summary>PID: 3 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodertitleparameter_3 = 3;
	/// <summary>PID: 3 | Type: read</summary>
	public const int decodertitleparameter = 3;
	/// <summary>PID: 4 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderstatusparam_4 = 4;
	/// <summary>PID: 4 | Type: read</summary>
	public const int encoderstatusparam = 4;
	/// <summary>PID: 5 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatusparam_5 = 5;
	/// <summary>PID: 5 | Type: read</summary>
	public const int decoderstatusparam = 5;
	/// <summary>PID: 6 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrateparameter_6 = 6;
	/// <summary>PID: 6 | Type: read</summary>
	public const int encodercurrentcompressedbitrateparameter = 6;
	/// <summary>PID: 7 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrateparameter_7 = 7;
	/// <summary>PID: 7 | Type: read</summary>
	public const int decodercurrentcompressedbitrateparameter = 7;
	/// <summary>PID: 8 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweight_8 = 8;
	/// <summary>PID: 8 | Type: read</summary>
	public const int encoderautochromaweight = 8;
	public class Write
	{
		/// <summary>PID: 54 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderstatusparam_54 = 54;
		/// <summary>PID: 54 | Type: write</summary>
		public const int encoderstatusparam = 54;
		/// <summary>PID: 55 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatusparam_55 = 55;
		/// <summary>PID: 55 | Type: write</summary>
		public const int decoderstatusparam = 55;
		/// <summary>PID: 58 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderautochromaweight_58 = 58;
		/// <summary>PID: 58 | Type: write</summary>
		public const int encoderautochromaweight = 58;
	}
}
public class WriteParameters
{
	/// <summary>PID: 54  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Encoderstatusparam {get { return Protocol.GetParameter(54); }set { Protocol.SetParameter(54, value); }}
	/// <summary>PID: 55  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Decoderstatusparam {get { return Protocol.GetParameter(55); }set { Protocol.SetParameter(55, value); }}
	/// <summary>PID: 58  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Encoderautochromaweight {get { return Protocol.GetParameter(58); }set { Protocol.SetParameter(58, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Encodertitleparameter_1 { get; set; }
	object Encodertitleparameter { get; set; }
	object Afterstartup_dummy { get; set; }
	object Decodertitleparameter_3 { get; set; }
	object Decodertitleparameter { get; set; }
	object Encoderstatusparam_4 { get; set; }
	object Encoderstatusparam { get; set; }
	object Decoderstatusparam_5 { get; set; }
	object Decoderstatusparam { get; set; }
	object Encodercurrentcompressedbitrateparameter_6 { get; set; }
	object Encodercurrentcompressedbitrateparameter { get; set; }
	object Decodercurrentcompressedbitrateparameter_7 { get; set; }
	object Decodercurrentcompressedbitrateparameter { get; set; }
	object Encoderautochromaweight_8 { get; set; }
	object Encoderautochromaweight { get; set; }
	object Encoderstatusparam_54 { get; set; }
	object Decoderstatusparam_55 { get; set; }
	object Encoderautochromaweight_58 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodertitleparameter_1 {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 1  | Type: read</summary>
	public System.Object Encodertitleparameter {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodertitleparameter_3 {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 3  | Type: read</summary>
	public System.Object Decodertitleparameter {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatusparam_4 {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 4  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Encoderstatusparam {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatusparam_5 {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 5  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Decoderstatusparam {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Avilable = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrateparameter_6 {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 6  | Type: read | EXCEPTIONS: Not Avilable = -1</summary>
	public System.Object Encodercurrentcompressedbitrateparameter {get { return GetParameter(6); }set { SetParameter(6, value); }}
	/// <summary>PID: 7  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrateparameter_7 {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 7  | Type: read</summary>
	public System.Object Decodercurrentcompressedbitrateparameter {get { return GetParameter(7); }set { SetParameter(7, value); }}
	/// <summary>PID: 8  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_8 {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 8  | Type: read | DISCREETS: Enabled = 1, Disabled = 0</summary>
	public System.Object Encoderautochromaweight {get { return GetParameter(8); }set { SetParameter(8, value); }}
	/// <summary>PID: 54  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatusparam_54 {get { return GetParameter(54); }set { SetParameter(54, value); }}
	/// <summary>PID: 55  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatusparam_55 {get { return GetParameter(55); }set { SetParameter(55, value); }}
	/// <summary>PID: 58  | Type: write | DISCREETS: Enabled = 1, Disabled = 0</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_58 {get { return GetParameter(58); }set { SetParameter(58, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
